# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest nuitka
        pip install -r requirements.txt
    - name: Build with nuitka
      run: |
        nuitka --standalone --assume-yes-for-downloads --follow-imports --include-package=sakura --include-data-dir=resources=resources --include-data-file=config.yaml=config.yaml --windows-icon-from-ico=resources/static/icon/logo-64x64.ico --windows-console-mode=disable --enable-plugin=pyside6 --mingw64 .\gui.py
    - name: Create zip
      run: |
        Compress-Archive -Path "gui.dist" -DestinationPath "gui.dist.zip"
    - name: Upload zip
      uses: actions/upload-artifact@v3
      with:
        name: gui.dist.zip
        path: 'gui.dist.zip'